---
- name: restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: reload & restart systemd service
  ansible.builtin.systemd:
    name: backend.service
    state: restarted
    daemon_reload: yes
  become: true