---
plugin: amazon.aws.aws_ec2
regions:
- us-west-2

compose:
ansible_host: public_dns_name

keyed_groups:

- key: tags.Name
  prefix: ""
  separator: ""

- key: tags.Project
  prefix: ""
  separator: ""

- key: tags.Server_Type
  prefix: ""
  separator: ""

  